config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  get '/', to: 'main#index'
  get 'index', to: 'main#index'

  get '/admin_login', to: 'admin_sessions#new'
  post '/admin_login', to: 'admin_sessions#create'
  delete '/admin_logout', to: 'admin_sessions#destroy'

  get 'home/terms', to: 'home#terms'
  get 'home/policy', to: 'home#policy'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  get 'users/confirm', to: 'users#confirm'
  post 'users/confirm', to: 'users#confirm'
  get 'users/back', to: 'users#back'
  post 'users/back', to: 'users#back'
  get 'signup_done', to: 'users#signup_done'
  get 'success', to: 'users#success'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/mail_done'
  get 'password_resets/success'

  resources :works
  resources :work_cats
  resources :articles
  resources :article_cats
  resources :news
  resources :news_cats
  resources :cart_works
  post 'cart_works/delete', to: 'cart_works#delete'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'admin', to: 'main#admin'
  get 'admin_view', to: 'main#admin_view'
  post 'delete', to: 'main#delete'
  get 'concept', to: 'main#concept'
  get 'purchase', to: 'main#purchase'
  get 'thanks', to: 'main#thanks'
  get 'help', to: 'main#help'
  get 'terms', to: 'main#terms'
  get 'policy', to: 'main#policy'

  get 'doraemon', to: 'doraemon#doraemon'
  post 'doraemon', to: 'doraemon#doraemon'

  get 'contact', to: 'contacts#new'
  resources :contacts, only: [:create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/done', to: 'contacts#done', as: 'done'

end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController
  layout 'main'

  def new
  end

  def create
    admin = Admin.find_by(name: params[:session][:name])
    if admin && admin.authenticate(params[:session][:password])
      admin_log_in admin
      redirect_to '/admin'
    else
      render 'new'
    end
  end

  def destroy
    admin_log_out if admin_logged_in?
    redirect_to '/admin'
  end
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
    def admin_log_in(admin)
        session[:admin_id] = admin.id
    end

    def current_admin
        if session[:admin_id]
          @current_admin ||= Admin.find_by(id: session[:admin_id])
        end
    end

    def current_admin?(admin)
        admin == current_admin
    end

    def admin_logged_in?
        !current_admin.nil?
    end
    
    def admin_log_out
        session.delete(:admin_id)
        @current_admin = nil
    end
end

app/views/admin_sessions/new.html.erb
<% if admin_logged_in? %>
    <div id="cxxsew-contents">
        <div class="article">
            <h1>- ADMINにログイン中 -</h1>
            <%= link_to "管理画面トップへ", '/admin', class:'btn', id:"submit-btn" %>
        </div>
    </div>
<% else %>

    <div id="cxxsew-contents">
        <div class="article">
            <h1>- 管理者専用ログイン画面 -</h1>
            
            <%= form_for(:session, url: admin_login_path) do |f| %>
                <label for="email">ID</label>
                    <%= f.text_field :name, placeholder:'管理者IDを入力してください' %>
                <label for="password">パスワード</label>
                    <%= f.password_field :password, placeholder:'パスワードを入力してください'  %>
                <%= f.submit 'Log in', class:'btn', id:"submit-btn" %>
            <% end %>
        </div>
    </div>
<% end %>