config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  get '/', to: 'main#index'
  get 'index', to: 'main#index'

  get '/admin_login', to: 'admin_sessions#new'
  post '/admin_login', to: 'admin_sessions#create'
  delete '/admin_logout', to: 'admin_sessions#destroy'

  get 'home/terms', to: 'home#terms'
  get 'home/policy', to: 'home#policy'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  get 'users/confirm', to: 'users#confirm'
  post 'users/confirm', to: 'users#confirm'
  get 'users/back', to: 'users#back'
  post 'users/back', to: 'users#back'
  get 'signup_done', to: 'users#signup_done'
  get 'success', to: 'users#success'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/mail_done'
  get 'password_resets/success'

  resources :works
  resources :work_cats
  resources :articles
  resources :article_cats
  resources :news
  resources :news_cats
  resources :cart_works
  post 'cart_works/delete', to: 'cart_works#delete'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'admin', to: 'main#admin'
  get 'admin_view', to: 'main#admin_view'
  post 'delete', to: 'main#delete'
  get 'concept', to: 'main#concept'
  get 'purchase', to: 'main#purchase'
  get 'thanks', to: 'main#thanks'
  get 'help', to: 'main#help'
  get 'terms', to: 'main#terms'
  get 'policy', to: 'main#policy'

  get 'doraemon', to: 'doraemon#doraemon'
  post 'doraemon', to: 'doraemon#doraemon'

  get 'contact', to: 'contacts#new'
  resources :contacts, only: [:create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/done', to: 'contacts#done', as: 'done'

end

app/views/shared/_footer.html.erb
<footer>
	<a href="/" id="ft-center">
		<div>MANIACS</div>
	</a>
	<p>代表取締役: 駒井 隆司</p>
	<p>石川県金沢市利家城下町100万石</p>
	<p>aaa@example.com</p>
	<div class="help-wrapper">
		<a href="/help">HELP</a>
		<a href="/contact">CONTACT</a>
		<a href="/policy">POLICY</a>
		<a href="/terms">TERMS</a>
	</div>
	<ul class="follow-links">
		<li class="follow-link"><a href="https://twitter.com" target="_blank"><%= image_tag "/svg/twiiter_w.svg", alt:"", class:"icon" %></a></li>
		<li class="follow-link"><a href="https://ja-jp.facebook.com" target="_blank"><%= image_tag "/svg/facebook_w.svg", alt:"", class:"icon" %></a></li>
		<li class="follow-link"><a href="https://www.instagram.com" target="_blank"><%= image_tag "/svg/instagram_w.svg", alt:"", class:"icon" %></a></li>
		<li class="follow-link"><a href="https://line.me" target="_blank"><%= image_tag "/svg/line_w.svg", alt:"", class:"icon" %></a></li>
	</ul>
	<small>(C) 2023 MANIACS.Inc All Rights Reserved.</small>
</footer>

app/views/shared/_header.html.erb
<header id="top-header">
	<div id="hd-flex">
		<a href="/">
			<div class="hd-side pf-side pc">LOGO</div>
		</a>
		<div class="toggle-btn sp">
			<div id="cross">
				<span class="menu-line-top"></span>
				<span class="menu-line-middle"></span>
				<span class="menu-line-bottom"></span>
			</div>
		</div>
		<a href="/" class="pf-hd-center" id="hd-center">
			<div>MANIACS</div>
		</a>
		<% if admin_logged_in? %>
			<%= link_to "Log out", admin_logout_path, method: :delete, class:"hd-side admin-hd-side" %>
		<% else %>
			<% if logged_in? %>
				<%= link_to "Log out", logout_path, method: :delete, class:"hd-side pf-side" %>
			<% else%>
				<a href="/login" id="hd-right">
					<div class="hd-side pf-side pc">log in</div>
					<div class="sp" id="sp-side">
						<svg width="100%" height="100%" viewBox="-150 -150 300 300">
							<path d="M142 -47 L88 121 L-89 121 L-143 -47 L-1 -150 z" stroke="#fff" fill="none" stroke-width="4"></path>
						</svg>
						<div>log in</div>
					</div>
				</a>
			<% end %>
		<% end %>
	</div>
</header>

<div class="hidden sp" id="sp-bg"></div>
<div class="hidden sp" id="sp-menu">
	<h1 class="menu-h2">- Menu -</h1>
	<div class="btn be-pink"><a href="/works">Works</a></div>
	<div class="btn be-pink"><a href="/articles">Articles</a></div>
	<div class="btn be-pink"><a href="/news">Comics</a></div>
	<div class="explain">
		<div class="rect-wrapper" id="sub-menu2">
			<a href="/help">HELP</a>
			<a href="/contact">CONTACT</a>
			<a href="/policy">POLICY</a>
			<a href="/terms">TERMS</a>
		</div>
	</div>
	<div id="menu-close">×</div>
</div>

<% if @cart.present? and @cart.cart_works.length != 0 %>
	<a href="/purchase" id="cart-sign">
		<%= image_tag '/image/cart.png', alt:"" %>
	</a>
<% end %>

<div class="brand-theme">まっさらのままで 風に吹かれて</div>
	  